### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by egorzainullin** [Zero-to-Heroes/firestone#25]
Hello, that's me again. 
Firtst of all, I want to report some small bugs
Bugs:
I got this achievment but I was not in Diamond at this moment
![image](https://user-images.githubusercontent.com/22919120/84596581-43c3ee80-ae67-11ea-9d1a-5aee4e087bac.png)

Some strange picture on ranked replay
![image](https://user-images.githubusercontent.com/22919120/84596567-34dd3c00-ae67-11ea-8610-398e9b07fba2.png)

Also I have some suggestions about the app.
1) Localisation. It would be great, if you have this opportunity to users to translate this app, may be by pull request or something. 
2) BG. To my mind it's not convenient to press alt+b all the time. May be add some picture with probability of winning in the screen, like in HS deck tracker.

Thank you for your app, btw

**Comment by egorzainullin** [comment]
Oh, PS about subscrption. May be add subscription per year with some discount and one-time purchase(I prefer this one)

**Comment by sebastientromp** [comment]
Hey, thanks for all the reports and suggestions!

>  I got this achievment but I was not in Diamond at this moment

Was the match you played before that one in Diamond?

> Some strange picture on ranked replay

This happens when the image is missing. Do you remember what league / rank you were playing at?

> Localisation. It would be great, if you have this opportunity to users to translate this app, may be by pull request or something.

To be honest, this is something I've been postponing for ages. In my previous endeavor, I had localization from the start, and over the course the of the life of the development it cost me many hours (because I had to localize everything I did).  
It's of course something I want to do in the future, but I'm not sure yet when / how I want to approach that.

> BG. To my mind it's not convenient to press alt+b all the time. May be add some picture with probability of winning in the screen, like in HS deck tracker.

This as well is on my roadmap (but not at the top :P). Basically I want to split the interesting bits of the screen into smaller widgets, and the win chance is the obvious candidate for that.

> May be add subscription per year with some discount 

That's a good suggestion, I'll pass it around (Overwolf are the ones who handle the subscription stuff).

> one-time purchase(I prefer this one)

For this to work I would really have to figure out the financials. From my experience I've found that it's much easier for people to spend $3 per month for a year than to spend $50 a single time, even if in the long term it's cheaper for them.  
To be clear, it's something I'd like to have, but I have to be very cautious about how I approach it.

Thanks again for all the suggestions and reports!
