### ISSUE TITLE
Mercs abilities highlighted when shouldn't

### ISSUE THREAD

**Issue by piedpiper358** [Zero-to-Heroes/firestone#268]
@sebastientromp, mercs abilities highlighted when shouldn't. 

![2022-10-20_01-31-48](https://user-images.githubusercontent.com/43519401/197415968-c1f6a4ed-6f05-4c59-8ca6-f67fa14de68b.png)

![2022-10-20_01-41-00](https://user-images.githubusercontent.com/43519401/197415970-4131d6ed-b26e-4b61-b655-1e46eef1fae8.png)

**Comment by sebastientromp** [comment]
I would need to have the logs to understand what's going on. How did the synergies appear in the first place?

**Comment by piedpiper358** [comment]
Perhaps this is due to getting Bonus Loot or Cursed Treasure in the Mystery node.

**Comment by sebastientromp** [comment]
I think it happens when the memory reading module resets while you are selecting a treasure, and that you complete the treasure selection before the reset occurs.
I will see if I can fix this

**Comment by piedpiper358** [comment]
By the way, these resets happen quite often for me and notifications about them interfere with pressing  in-game buttons. Than it can be caused?

![2022-09-19_22-58-12 2](https://user-images.githubusercontent.com/43519401/200828004-6c9a1acc-c728-4357-a2e2-0c3c0db19a87.png)



Maybe the problem can be solved by checking the current scene?

**Comment by sebastientromp** [comment]
I have a fix ready. Checking the current scene fixes the symptoms, but not the underlying root cause (which is that, after a reset, some of the initial memory state is not properly populated).

The memory resets are caused by the game's internal memory structure changing. For now, the only solution I have to cope with this is to reset the app's memory reading plugin. There might be better solutions, but I'm out of my depth here.
They appear only on the dev version, and if they bother you you can either turn off the notifications, or simply close the notifs.
