### ISSUE TITLE
Detect deck versions

### ISSUE THREAD

**Issue by GCorbel** [Zero-to-Heroes/firestone#320]
Each time we change a card in a deck, the tracker creates a completely new one. Given that, stats are split.

Changing cards in a deck should create a new version of this deck. I am not sure of when a deck should be considered as a new version or a new one.

**Comment by sebastientromp** [comment]
The decision on when to create a new deck is not an easy one, and it's sometimes a bit subjective. That's why Firestone creates a new deck every time.

You can however easily merge decks together. In the Decks view, you can drag and drop a deck into another, which will create a new version of the deck. Then, when you go into the deck details, you can view all the versions, rearrange them however you like, and see stars for either the all versions combien combined, it just one of them.

Hope this helps!

**Comment by GCorbel** [comment]
I agree, maybe the auto-detection of version is not necessary. Maybe just clarify how to do versions is enough.

On the "my decks" page, a "merge with" button can be available after the one to delete a deck. When this button is selected, the dragging is started. The dragging can be cancelled when a click is performed anywhere.

**Comment by GCorbel** [comment]
it's done. Thanks.
