### ISSUE TITLE
Profile->BG shows wrong winrate and total matches

### ISSUE THREAD

**Issue by 2813** [Zero-to-Heroes/firestone#343]
![image](https://github.com/user-attachments/assets/71d2add3-d32f-438e-a5b7-572747d8ced7)

**Comment by sebastientromp** [comment]
Hello, thanks for the report!
This is because of an internal change that was made in the game client. Unfortunately, the "total matches" info won't be available anymore moving forward, and I will remove that piece of info, as well as the Winrate.
I will instead add a new tab in the BG section to show your personal stats, but they will only include games you've played with Firestone on.
